CREATE TABLE IF NOT EXISTS USERS (
    USERNAME VARCHAR(128) PRIMARY KEY ,
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED BOOLEAN

);


CREATE TABLE IF NOT EXISTS AUTHORITIES (
    USERNAME VARCHAR(128) NOT NULL,
    AUTHORITY VARCHAR(128) NOT NULL,
    CONSTRAINT fk_authorities_users 
    FOREIGN KEY(USERNAME) 
    REFERENCES USERS(USERNAME)
);
